spring.application.name=web-khachsan-nhom2

spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=QuanLyKhachSan;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;
spring.datasource.username=sa
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.thymeleaf.encoding=UTF-8


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vocuong1272@gmail.com
spring.mail.password=qfdnriodkcwtwcuh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true